pip install opencv-python

import cv2
print(cv2.__version__)


In [1]:
import cv2

In [2]:
import numpy as np

# Load/Read image

In [3]:
# load an image using 'imread' specifying the path to image

In [4]:
img = cv2.imread(r"C:\Users\L.RAMYA\Downloads\Modi.jpg",1)

In [5]:
type(img)

numpy.ndarray

In [6]:
img.ndim

3

In [7]:
img.shape

(1358, 1500, 3)

In [8]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [9]:
# display the image
cv2.imshow('Pm',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
img.shape

(1358, 1500, 3)

In [11]:
# Resize Image

In [12]:
img = cv2.imread(r"C:\Users\L.RAMYA\Downloads\Modi.jpg",1)

resized_image = cv2.resize(img,(679,750))

cv2.imshow('Prime minister',resized_image)
cv2.waitKey()
cv2.destroyAllWindows()


**convert color image to black and white image**

In [13]:
img = cv2.imread(r"C:\Users\L.RAMYA\Downloads\Modi.jpg",1)  # 1358*1500(color)

resized_image = cv2.resize(img,(679,750))     # 679*750(color)

gray = cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY) # 679*750(b/w)

cv2.imshow('Prime minister sir',gray) # you can change the name like resized_image(colorimg) or gray(b/w)
cv2.waitKey()
cv2.destroyAllWindows()

# SAVE image

In [14]:
# simply use "imwrite' specifing the file name and the image to be saved
cv2.imwrite('bw.jpg',gray)

True

# Computer vision
1. object detection as per your requirements
2. if you want to detect human face , it detect human face
3. if you to detect mobile ,it detect mobile within the given image

In [15]:
img = cv2.imread(r"C:\Users\L.RAMYA\Downloads\Modi.jpg",1)  # 1358*1500(color)

resized_image = cv2.resize(img,(679,750))     # 679*750(color)

gray = cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY) # 679*750(b/w)


# Face Detection using HAAR cascade Classifiers

In [16]:
import cv2

# Load Haar cascade from OpenCV's default location
face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# Check if the classifier loaded correctly
if face_classifier.empty():
    print("Error: Haar cascade file not found!")
else:
    print("Haar cascade loaded successfully.")


Haar cascade loaded successfully.


In [17]:
# Matching the features on given image

faces = face_classifier.detectMultiScale(gray,1.5,5)

In [18]:
faces

array([[292, 145, 273, 273]])

In [19]:
import cv2

# Load Haar cascade from OpenCV's default location
face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# Check if the classifier loaded correctly
if face_classifier.empty():
    print("Error: Haar cascade file not found!")
else:
    print("Haar cascade loaded successfully.")
# load the image

image = cv2.imread(r"C:\Users\L.RAMYA\Downloads\Modi.jpg",1)  # 1358*1500(color)

resized_image = cv2.resize(img,(679,750))     # 679*750(color)

gray = cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY) # 679*750(b/w)


faces = face_classifier.detectMultiScale(gray,1.1,5)

if faces is():
    print ('no faces found')

else:
    for (x,y,l,h) in faces:
        cv2.rectangle(resized_image,(x,y),(x+l,y+h),(255,0,0),1)

cv2.imshow('face detection',resized_image)
cv2.waitKey()
cv2.destroyAllWindows()


<>:22: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
<>:22: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
C:\Users\L.RAMYA\AppData\Local\Temp\ipykernel_18524\1313148464.py:22: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
  if faces is():


Haar cascade loaded successfully.


In [20]:
import cv2

# Load Haar cascade from OpenCV's default location
face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')  # Fixed eye cascade

# Check if the classifiers loaded correctly
if face_classifier.empty():
    print("Error: Face cascade file not found!")
if eye_classifier.empty():
    print("Error: Eye cascade file not found!")

# Load the image
image = cv2.imread(r"C:\Users\L.RAMYA\Downloads\Modi.jpg")

# Check if the image is loaded correctly
if image is None:
    print("Error: Image not found!")
else:
    # Resize the image
    resized_image = cv2.resize(image, (679, 750))  

    # Convert to grayscale
    gray = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)

    # Detect faces
    faces = face_classifier.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5)

    # Check if faces were found
    if len(faces) == 0:
        print("No faces found")
    else:
        print(f"Faces found: {len(faces)}")

        # Draw rectangles around detected faces
        for (x, y, w, h) in faces:
            cv2.rectangle(resized_image, (x, y), (x + w, y + h), (255, 0, 0), 3)

            # Detect eyes within the detected face region
            roi_gray = gray[y:y+h, x:x+w]
            roi_color = resized_image[y:y+h, x:x+w]
            eyes = eye_classifier.detectMultiScale(roi_gray, scaleFactor=1.05, minNeighbors=5)

            for (ex, ey, ew, eh) in eyes:
                cv2.rectangle(roi_color, (ex, ey), (ex + ew, ey + eh), (0, 255, 0), 2)

        # Show the image with detected faces and eyes
        cv2.imshow("Face and Eye Detection", resized_image)
        cv2.waitKey(0)
        cv2.destroyAllWindows()



Faces found: 1


# capture video

# doing some face recoginition with the webcam

import cv2
video = cv2.VideoCapture(0)

while True:
    check,frame = video.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    canvas = detect(gray,frame)
    cv2.imshow('video',frame)
    if cv2.waitKey(1) == ord('q'):
        break
video.release()
cv2.destroyAllWindows()
     

In [1]:
import cv2

# Load Haar cascades for face and eye detection
face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

# Check if cascades loaded correctly
if face_classifier.empty():
    print("Error: Face cascade file not found!")
if eye_classifier.empty():
    print("Error: Eye cascade file not found!")

def detect(gray,frame):

    # Detect faces
    faces = face_classifier.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5)

    for (x, y, w, h) in faces:
        # Draw rectangle around face
        cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 0, 0), 3)

        # Detect eyes within face ROI
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_classifier.detectMultiScale(roi_gray, scaleFactor=1.1, minNeighbors=5)

        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(roi_color, (ex, ey), (ex + ew, ey + eh), (0, 255, 0), 2)
    return frame
# doing some face recognition with the webcame
video = cv2.VideoCapture(0)
while True:
    check,frame = video.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    canvas = detect(gray,gray)
    cv2.imshow('video',gray)
    if cv2.waitKey(1) == ord('q'):
        break

# Release webcam and close windows
video.release()
cv2.destroyAllWindows()


In [2]:
import cv2

# Load Haar cascades for face and eye detection
face_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_classifier = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

# Check if cascades loaded correctly
if face_classifier.empty():
    print("Error: Face cascade file not found!")
if eye_classifier.empty():
    print("Error: Eye cascade file not found!")

def detect(gray, frame):
    # Detect faces
    faces = face_classifier.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5)

    for (x, y, w, h) in faces:
        # Draw rectangle around face (Blue)
        cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 0, 0), 3)

        # Detect eyes within face ROI
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_classifier.detectMultiScale(roi_gray, scaleFactor=1.1, minNeighbors=5)
qq
        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(roi_color, (ex, ey), (ex + ew, ey + eh), (0, 255, 0), 2)  # Green for eyes
    return frame

# Start webcam
video = cv2.VideoCapture(0)

while True:
    check, frame = video.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    canvas = detect(gray, frame)  # Detect faces and eyes

    cv2.imshow('Face & Eye Detection', canvas)  # ✅ FIXED: Show color image with detections

    if cv2.waitKey(1) == ord('q'):  # Press 'q' to exit
        break

# Release webcam and close windows
video.release()
cv2.destroyAllWindows()
